sudo: false
language: java
jdk:
- oraclejdk7
after_success:
- ".buildscript/deploy_snapshot.sh"
install: true
script:
- travis_wait mvn -q clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
branches:
  except:
  - travis
cache:
  directories:
    - $HOME/.m2
env:
  global:
  - secure: "q6oLIb4TpyVxy6jcauijVcGkkTr3xe5dfcII5yJs48r2FzcZeAYqPvifb9G9tlOiK5igXJrEa2GmNytlI9NijOIAt8BBV34xIovwkupwJ9qGAxG2E5hHbAjGiRaICTglkH+psgaPuPe4W8UgmWCSNt9bM12F1bVHsXXftWx/880="
  - secure: "VYSXB7Myuqbkyt9vjiro09R6e44G2xAie8Q8lYfJreghp7kTIUeH3cCY9gMRb8pMiYadVtF01hzJWaf6PaApScNivmMUkvzGGvfnRX1FbBoxL9CIhkZkmofoyvqiobE4moZpDl6wje7APAch2b/D9Q4CmNQf7eBFic9XissQqA4="
  - secure: "LDY2kwDizqBSz0NzkKpTYvPXkyibFfXEgFUcPsfYyONXXMsWSNVQFidBru0x20MFRrd6TaHnTwuyTEpPhWCpaBn2k3K7NyLo5LvQOIpTCiqZHehjXQiLb6u8+YWcufBp4k2kOipscSUlTyvAJ9y+VCnsEb/aoK55lSBIEejB7Rs="
  - secure: "UfSHzH9MgNLpMSknx4sLGLlTtslWb7xASgh4xo0sTnxhbkTl3MeR6qg81NwQMhe8bbg81ucVApmfSmmTuy0HM1w7/KZjo6xwXUj5KmoDoO28CrEajE1IzV+SEA9RGvH1N3VD45mumcD34t5qXGQUnix3oVOaL4wSvVTpkWqYd1I="
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/616eadc01d54389d624f
    on_success: change
    on_failure: always
    on_start: false
